# coding: utf-8

"""
    madana-api

    <h1>API Quickstart Guide</h1>        <p>This documentation contains a Quickstart Guide, a few <a href=\"downloads.html\">sample clients</a>  for download and information about the available  <a href=\"resources.html\">endpoints</a>  and  <a href=\"data.html\">DataTypes</a>  </p>     <p>The <a target=\"_blank\" href=\"http://madana-explorer-staging.eu-central-1.elasticbeanstalk.com/login\">  MADANA Explorer</a> can be used to verify the interactions with the API</p>           <p>Internal use only. For more information visit <a href=\"https://www.madana.io\">www.madana.io</a></p>         <br> <br>  # noqa: E501

    The version of the OpenAPI document: 0.4.12
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import madana_sampleclient_python
from madana_sampleclient_python.api.social_service_api import SocialServiceApi  # noqa: E501
from madana_sampleclient_python.rest import ApiException


class TestSocialServiceApi(unittest.TestCase):
    """SocialServiceApi unit test stubs"""

    def setUp(self):
        self.api = madana_sampleclient_python.api.social_service_api.SocialServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_my_profile(self):
        """Test case for get_my_profile

        """
        pass

    def test_get_platforms2(self):
        """Test case for get_platforms2

        Returns all Platforms / Systems that can be Connected to the MADANA Service.  # noqa: E501
        """
        pass

    def test_get_ranking(self):
        """Test case for get_ranking

        Returns the Ranking by PTS within the System.  # noqa: E501
        """
        pass

    def test_get_social_platform_feed(self):
        """Test case for get_social_platform_feed

        """
        pass

    def test_get_user_profile(self):
        """Test case for get_user_profile

        """
        pass

    def test_get_user_profile_0(self):
        """Test case for get_user_profile_0

        """
        pass


if __name__ == '__main__':
    unittest.main()
