# coding: utf-8

"""
    madana-api

    <h1>API Quickstart Guide</h1>        <p>This documentation contains a Quickstart Guide, a few <a href=\"downloads.html\">sample clients</a>  for download and information about the available  <a href=\"resources.html\">endpoints</a>  and  <a href=\"data.html\">DataTypes</a>  </p>     <p>The <a target=\"_blank\" href=\"http://madana-explorer-staging.eu-central-1.elasticbeanstalk.com/login\">  MADANA Explorer</a> can be used to verify the interactions with the API</p>           <p>Internal use only. For more information visit <a href=\"https://www.madana.io\">www.madana.io</a></p>         <br> <br>  # noqa: E501

    The version of the OpenAPI document: 0.4.12
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import madana_sampleclient_python
from madana_sampleclient_python.api.account_service_api import AccountServiceApi  # noqa: E501
from madana_sampleclient_python.rest import ApiException


class TestAccountServiceApi(unittest.TestCase):
    """AccountServiceApi unit test stubs"""

    def setUp(self):
        self.api = madana_sampleclient_python.api.account_service_api.AccountServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_activate_user(self):
        """Test case for activate_user

        """
        pass

    def test_create_object(self):
        """Test case for create_object

        Sends an Password reset mail to the given MailAddress.  # noqa: E501
        """
        pass

    def test_request_verification_mail(self):
        """Test case for request_verification_mail

        Used to request a new  activation-mail for the user.  # noqa: E501
        """
        pass

    def test_update_object(self):
        """Test case for update_object

        Receives the Password reset and tries to set the provided password for the user.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
