# coding: utf-8

"""
    madana-api

    <h1>API Quickstart Guide</h1>        <p>This documentation contains a Quickstart Guide, a few <a href=\"downloads.html\">sample clients</a>  for download and information about the available  <a href=\"resources.html\">endpoints</a>  and  <a href=\"data.html\">DataTypes</a>  </p>     <p>The <a target=\"_blank\" href=\"http://madana-explorer-staging.eu-central-1.elasticbeanstalk.com/login\">  MADANA Explorer</a> can be used to verify the interactions with the API</p>           <p>Internal use only. For more information visit <a href=\"https://www.madana.io\">www.madana.io</a></p>         <br> <br>  # noqa: E501

    The version of the OpenAPI document: 0.4.12
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import madana_sampleclient_python
from madana_sampleclient_python.api.authentication_service_api import AuthenticationServiceApi  # noqa: E501
from madana_sampleclient_python.rest import ApiException


class TestAuthenticationServiceApi(unittest.TestCase):
    """AuthenticationServiceApi unit test stubs"""

    def setUp(self):
        self.api = madana_sampleclient_python.api.authentication_service_api.AuthenticationServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_authenticate_application(self):
        """Test case for authenticate_application

        Authenticates a new application and returns the token.  # noqa: E501
        """
        pass

    def test_authenticate_ethereum_wallet(self):
        """Test case for authenticate_ethereum_wallet

        """
        pass

    def test_authenticate_user(self):
        """Test case for authenticate_user

        Authenticates a new user and returns the token (  forbidden if the credentials cannot be validated ).  # noqa: E501
        """
        pass

    def test_authenticate_with_ethereum_challenge(self):
        """Test case for authenticate_with_ethereum_challenge

        """
        pass

    def test_get_fractal_authentication_url(self):
        """Test case for get_fractal_authentication_url

        Returns the AUthorization URL to verify a Twitter Accounts.  # noqa: E501
        """
        pass

    def test_get_nonce_for_ethereum_wallet(self):
        """Test case for get_nonce_for_ethereum_wallet

        Returns a nonce for the client which is used as content for the to be created signature.  # noqa: E501
        """
        pass

    def test_get_object(self):
        """Test case for get_object

        Used to validate the active connection with the API.  # noqa: E501
        """
        pass

    def test_get_twitter_authentication_url(self):
        """Test case for get_twitter_authentication_url

        Returns the AUthorization URL to verify a Twitter Accounts.  # noqa: E501
        """
        pass

    def test_set_facebook_uid(self):
        """Test case for set_facebook_uid

        Used as Callback URL when users have successfully authorized their facbeook account.  # noqa: E501
        """
        pass

    def test_set_fractal_uid(self):
        """Test case for set_fractal_uid

        """
        pass

    def test_set_twitter_uid(self):
        """Test case for set_twitter_uid

        """
        pass


if __name__ == '__main__':
    unittest.main()
