# coding: utf-8

"""
    madana-api

    <h1>API Quickstart Guide</h1>        <p>This documentation contains a Quickstart Guide, a few <a href=\"downloads.html\">sample clients</a>  for download and information about the available  <a href=\"resources.html\">endpoints</a>  and  <a href=\"data.html\">DataTypes</a>  </p>     <p>The <a target=\"_blank\" href=\"http://madana-explorer-staging.eu-central-1.elasticbeanstalk.com/login\">  MADANA Explorer</a> can be used to verify the interactions with the API</p>           <p>Internal use only. For more information visit <a href=\"https://www.madana.io\">www.madana.io</a></p>         <br> <br>  # noqa: E501

    The version of the OpenAPI document: 0.4.12
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import madana_sampleclient_python
from madana_sampleclient_python.models.json_analysis import JsonAnalysis  # noqa: E501
from madana_sampleclient_python.rest import ApiException

class TestJsonAnalysis(unittest.TestCase):
    """JsonAnalysis unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test JsonAnalysis
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = madana_sampleclient_python.models.json_analysis.JsonAnalysis()  # noqa: E501
        if include_optional :
            return JsonAnalysis(
                created = '0', 
                uuid = '0', 
                status = '0', 
                agent = '0', 
                datasets = [
                    null
                    ], 
                participants = [
                    '0'
                    ], 
                views = '0', 
                actions = [
                    {requestID=..., user=..., connection=..., date=..., fingerprint=..., application=..., action=..., details=..., signature=...}
                    ], 
                creator = '0', 
                dataset_count = '0'
            )
        else :
            return JsonAnalysis(
        )

    def testJsonAnalysis(self):
        """Test JsonAnalysis"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
