# coding: utf-8

"""
    madana-api

    <h1>API Quickstart Guide</h1>        <p>This documentation contains a Quickstart Guide, a few <a href=\"downloads.html\">sample clients</a>  for download and information about the available  <a href=\"resources.html\">endpoints</a>  and  <a href=\"data.html\">DataTypes</a>  </p>     <p>The <a target=\"_blank\" href=\"http://madana-explorer-staging.eu-central-1.elasticbeanstalk.com/login\">  MADANA Explorer</a> can be used to verify the interactions with the API</p>           <p>Internal use only. For more information visit <a href=\"https://www.madana.io\">www.madana.io</a></p>         <br> <br>  # noqa: E501

    The version of the OpenAPI document: 0.4.12
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "madana-sampleclient-python"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="madana-api",
    author="OpenAPI Generator community",
    author_email="team@openapitools.org",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "madana-api"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description="""\
    &lt;h1&gt;API Quickstart Guide&lt;/h1&gt;        &lt;p&gt;This documentation contains a Quickstart Guide, a few &lt;a href&#x3D;\&quot;downloads.html\&quot;&gt;sample clients&lt;/a&gt;  for download and information about the available  &lt;a href&#x3D;\&quot;resources.html\&quot;&gt;endpoints&lt;/a&gt;  and  &lt;a href&#x3D;\&quot;data.html\&quot;&gt;DataTypes&lt;/a&gt;  &lt;/p&gt;     &lt;p&gt;The &lt;a target&#x3D;\&quot;_blank\&quot; href&#x3D;\&quot;http://madana-explorer-staging.eu-central-1.elasticbeanstalk.com/login\&quot;&gt;  MADANA Explorer&lt;/a&gt; can be used to verify the interactions with the API&lt;/p&gt;           &lt;p&gt;Internal use only. For more information visit &lt;a href&#x3D;\&quot;https://www.madana.io\&quot;&gt;www.madana.io&lt;/a&gt;&lt;/p&gt;         &lt;br&gt; &lt;br&gt;  # noqa: E501
    """
)
