# coding: utf-8

"""
    madana-api

    <h1>Using the madana-api</h1>        <p>This documentation contains a Quickstart Guide, relating client functionality and information about the available         endpoints and used datamodels.   </p>       <p> The madana-api and its implementations are still in heavy development. This means that there may be problems in our protocols, or there may be mistakes in our implementations. We take security vulnerabilities very seriously. If you discover a security issue, please bring it to our attention right away! If you find a vulnerability that may affect live deployments -- for example, by exposing a remote execution exploit -- please send your report privately to info@madana.io. Please DO NOT file a public issue. If the issue is a protocol weakness that cannot be immediately exploited or something not yet deployed, just discuss it openly   </p>   <br>   <p> Note: Not all functionality might be acessible without having accquired and api-license token. For more information visit <a href=\"https://www.madana.io\">www.madana.io</a> </p>       <br>  # noqa: E501

    The version of the OpenAPI document: 0.4.14-master.16
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from madana_sampleclient_python.configuration import Configuration


class JsonDiskConfig(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'roothash': 'str',
        'disk': 'str',
        'roothash_offset': 'int',
        'readonly': 'bool'
    }

    attribute_map = {
        'roothash': 'roothash',
        'disk': 'disk',
        'roothash_offset': 'roothash_offset',
        'readonly': 'readonly'
    }

    def __init__(self, roothash=None, disk=None, roothash_offset=None, readonly=None, local_vars_configuration=None):  # noqa: E501
        """JsonDiskConfig - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._roothash = None
        self._disk = None
        self._roothash_offset = None
        self._readonly = None
        self.discriminator = None

        if roothash is not None:
            self.roothash = roothash
        if disk is not None:
            self.disk = disk
        if roothash_offset is not None:
            self.roothash_offset = roothash_offset
        if readonly is not None:
            self.readonly = readonly

    @property
    def roothash(self):
        """Gets the roothash of this JsonDiskConfig.  # noqa: E501

          # noqa: E501

        :return: The roothash of this JsonDiskConfig.  # noqa: E501
        :rtype: str
        """
        return self._roothash

    @roothash.setter
    def roothash(self, roothash):
        """Sets the roothash of this JsonDiskConfig.

          # noqa: E501

        :param roothash: The roothash of this JsonDiskConfig.  # noqa: E501
        :type: str
        """

        self._roothash = roothash

    @property
    def disk(self):
        """Gets the disk of this JsonDiskConfig.  # noqa: E501

          # noqa: E501

        :return: The disk of this JsonDiskConfig.  # noqa: E501
        :rtype: str
        """
        return self._disk

    @disk.setter
    def disk(self, disk):
        """Sets the disk of this JsonDiskConfig.

          # noqa: E501

        :param disk: The disk of this JsonDiskConfig.  # noqa: E501
        :type: str
        """

        self._disk = disk

    @property
    def roothash_offset(self):
        """Gets the roothash_offset of this JsonDiskConfig.  # noqa: E501

          # noqa: E501

        :return: The roothash_offset of this JsonDiskConfig.  # noqa: E501
        :rtype: int
        """
        return self._roothash_offset

    @roothash_offset.setter
    def roothash_offset(self, roothash_offset):
        """Sets the roothash_offset of this JsonDiskConfig.

          # noqa: E501

        :param roothash_offset: The roothash_offset of this JsonDiskConfig.  # noqa: E501
        :type: int
        """

        self._roothash_offset = roothash_offset

    @property
    def readonly(self):
        """Gets the readonly of this JsonDiskConfig.  # noqa: E501

          # noqa: E501

        :return: The readonly of this JsonDiskConfig.  # noqa: E501
        :rtype: bool
        """
        return self._readonly

    @readonly.setter
    def readonly(self, readonly):
        """Sets the readonly of this JsonDiskConfig.

          # noqa: E501

        :param readonly: The readonly of this JsonDiskConfig.  # noqa: E501
        :type: bool
        """

        self._readonly = readonly

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JsonDiskConfig):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, JsonDiskConfig):
            return True

        return self.to_dict() != other.to_dict()
